### ISSUE TITLE
Base64 decoding not working

### ISSUE THREAD

**Issue by urbalazs** [reneeb/otrs-EmailDev#1]
Hi @reneeb 
The Base64 encoded names are not decoded in the list of development emails:

![decoding](https://cloud.githubusercontent.com/assets/1006118/20795341/fa0eac3e-b7d0-11e6-820f-a1fc9bb0d73b.png)

Now "To" field is:
    `=?UTF-8?B?w5pyIEJhbMOhenM=?= <urbalazs@gmail.com>`
Expected result:
    `Úr Balázs <urbalazs@gmail.com>`

**Comment by reneeb** [comment]
Thanks for the bugreport. The issue is fixed with commit af049c2
